package org.ugalileo.bean;
// Generated 12/02/2015 09:33:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Auxmateriaalumno generated by hbm2java
 */
public class Auxmateriaalumno  implements java.io.Serializable {


     private Integer idAuxMateriaAlumno;
     private Alumno alumno;
     private Materia materia;
     private Set notas = new HashSet(0);

    public Auxmateriaalumno() {
    }

	
    public Auxmateriaalumno(Alumno alumno, Materia materia) {
        this.alumno = alumno;
        this.materia = materia;
    }
    public Auxmateriaalumno(Alumno alumno, Materia materia, Set notas) {
       this.alumno = alumno;
       this.materia = materia;
       this.notas = notas;
    }
   
    public Integer getIdAuxMateriaAlumno() {
        return this.idAuxMateriaAlumno;
    }
    
    public void setIdAuxMateriaAlumno(Integer idAuxMateriaAlumno) {
        this.idAuxMateriaAlumno = idAuxMateriaAlumno;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }




}


