package org.ugalileo.bean;
// Generated 12/02/2015 09:33:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gradoseccion generated by hbm2java
 */
public class Gradoseccion  implements java.io.Serializable {


     private Integer idGradoSeccion;
     private String nombreGradoSeccion;
     private Set alumnos = new HashSet(0);

    public Gradoseccion() {
    }

	
    public Gradoseccion(String nombreGradoSeccion) {
        this.nombreGradoSeccion = nombreGradoSeccion;
    }
    public Gradoseccion(String nombreGradoSeccion, Set alumnos) {
       this.nombreGradoSeccion = nombreGradoSeccion;
       this.alumnos = alumnos;
    }
   
    public Integer getIdGradoSeccion() {
        return this.idGradoSeccion;
    }
    
    public void setIdGradoSeccion(Integer idGradoSeccion) {
        this.idGradoSeccion = idGradoSeccion;
    }
    public String getNombreGradoSeccion() {
        return this.nombreGradoSeccion;
    }
    
    public void setNombreGradoSeccion(String nombreGradoSeccion) {
        this.nombreGradoSeccion = nombreGradoSeccion;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }

    @Override
    public String toString() {
        return nombreGradoSeccion;
    }

    

}


