package org.ugalileo.bean;
// Generated 12/02/2015 09:33:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer idMateria;
     private String nombreMateria;
     private Set auxmateriaalumnos = new HashSet(0);

    public Materia() {
    }

	
    public Materia(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public Materia(String nombreMateria, Set auxmateriaalumnos) {
       this.nombreMateria = nombreMateria;
       this.auxmateriaalumnos = auxmateriaalumnos;
    }
   
    public Integer getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public Set getAuxmateriaalumnos() {
        return this.auxmateriaalumnos;
    }
    
    public void setAuxmateriaalumnos(Set auxmateriaalumnos) {
        this.auxmateriaalumnos = auxmateriaalumnos;
    }




}


